# Kafka Dockerfile
FROM bitnami/kafka:latest

ENV KAFKA_CFG_LISTENERS=INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092,CONTROLLER://:9093 \
KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka:29092,EXTERNAL://210.110.103.135:9092 \
KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT \
KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL \
KAFKA_CFG_NODE_ID=1 \
KAFKA_CFG_PROCESS_ROLES=controller,broker \
KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER \
KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@localhost:9093 \
ALLOW_PLAINTEXT_LISTENER=yes \
KAFKA_CFG_LOG_DIRS=/bitnami/kafka/data \
KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true

EXPOSE 29092 9092 9093

CMD ["/opt/bitnami/scripts/kafka/run.sh"]
